version: '3.1'
services:
  db-container:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Z4e2RzOC7O6XPncQZooa
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - "/app/data/rdbutils/mysql-data/db:/var/lib/mysql"

networks:
  default:
    name: proxy_default
